"""
prepare_yolo_split.py

Creates an 80/20 stratified Train+CV / Test split, then generates k-fold
cross-validation directories within the 80% portion for Optuna search,
plus a trainval/ directory for final retraining.

Layout produced:
  data/derived/yolo/
    test/images/  test/labels/        <- held-out 20%
    folds/fold_0/ ... fold_{k-1}/     <- each fold has data.yaml + train/val
    trainval/                          <- full 80% for final retraining
    fold_indices.json                  <- saved fold assignments
    data.yaml                          <- points to trainval (backward compat)
"""

import argparse
import json
import os
import shutil
import stat
import pathlib

import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold

REPO_ROOT = pathlib.Path(__file__).parent.resolve()
IMAGES_DIR = REPO_ROOT / "data" / "augmented_dataset_v2" / "images"
LABELS_FLAT = REPO_ROOT / "data" / "derived" / "yolo" / "labels"
YOLO_DIR = REPO_ROOT / "data" / "derived" / "yolo"
SAMPLES_PQ = REPO_ROOT / "data" / "augmented_dataset_v2" / "samples.parquet"

def _rm_readonly(func, path, _exc_info):
    """Handle read-only files on Windows / OneDrive by forcing write permission."""
    os.chmod(path, stat.S_IWRITE)
    func(path)


YAML_CLASSES = """\
nc: 2
names:
  0: cup
  1: timmies
"""


def write_data_yaml(path: pathlib.Path, root: pathlib.Path, train: str, val: str):
    """Write a YOLO-compatible data.yaml."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"# Auto-generated by prepare_yolo_split.py\n"
        f"path: {root}\n"
        f"train: {train}\n"
        f"val: {val}\n\n"
        f"{YAML_CLASSES}"
    )


def copy_or_link(src: pathlib.Path, dst: pathlib.Path):
    """Symlink preferred; falls back to copy on Windows without privileges."""
    if dst.exists():
        return
    try:
        dst.symlink_to(src.resolve())
    except OSError:
        shutil.copy2(src, dst)


def find_image(key: str, images_dir: pathlib.Path = IMAGES_DIR) -> pathlib.Path | None:
    """Locate the image file for a label key across common extensions."""
    for ext in (".jpg", ".jpeg", ".png", ".webp"):
        candidate = images_dir / (key + ext)
        if candidate.exists():
            return candidate
    return None


def populate_split(
    keys: list[str], img_dir: pathlib.Path, lbl_dir: pathlib.Path,
    images_dir: pathlib.Path = IMAGES_DIR,
) -> list[str]:
    """Copy/link images and labels into target dirs. Returns missing keys."""
    img_dir.mkdir(parents=True, exist_ok=True)
    lbl_dir.mkdir(parents=True, exist_ok=True)
    missing = []
    for key in keys:
        img_src = find_image(key, images_dir)
        if img_src is None:
            missing.append(key)
        else:
            copy_or_link(img_src, img_dir / img_src.name)

        lbl_src = LABELS_FLAT / (key + ".txt")
        lbl_dst = lbl_dir / (key + ".txt")
        if lbl_src.exists() and not lbl_dst.exists():
            shutil.copy2(lbl_src, lbl_dst)
    return missing


def parse_args():
    p = argparse.ArgumentParser(description="Prepare YOLO data with k-fold CV splits")
    p.add_argument("--k-folds", type=int, default=5,
                   help="Number of CV folds (default: 5)")
    p.add_argument("--seed", type=int, default=42,
                   help="Random seed for reproducibility (default: 42)")
    p.add_argument("--test-size", type=float, default=0.20,
                   help="Fraction held out for test (default: 0.20)")
    p.add_argument("--images-dir", default=None,
                   help="Override images directory (default: data/images)")
    p.add_argument("--samples-pq", default=None,
                   help="Override samples.parquet path")
    return p.parse_args()


def main():
    args = parse_args()
    k = args.k_folds
    seed = args.seed

    images_dir = pathlib.Path(args.images_dir) if args.images_dir else IMAGES_DIR
    samples_pq = pathlib.Path(args.samples_pq) if args.samples_pq else SAMPLES_PQ

    # ---- collect labelled keys ------------------------------------------------
    label_files = sorted(LABELS_FLAT.glob("*.txt"))
    label_files = [f for f in label_files if f.is_file() and f.parent == LABELS_FLAT]
    if not label_files:
        raise FileNotFoundError(f"No .txt label files found in {LABELS_FLAT}")

    keys = [f.stem for f in label_files]
    print(f"Found {len(keys)} labelled images.")
    print(f"Images dir: {images_dir}")
    print(f"Samples PQ: {samples_pq}")

    # ---- stratification labels ------------------------------------------------
    # 3-way: 0=hard_negative (no cups), 1=non-tim cups, 2=tim hortons
    df = pd.read_parquet(samples_pq, columns=["image_key", "has_tim_bbox", "n_det"])
    df["stem"] = (
        df["image_key"]
        .str.replace(r"^images/", "", regex=True)
        .str.replace(r"\.(jpg|jpeg|png|webp)$", "", regex=True)
    )
    key_to_tim = dict(zip(df["stem"], df["has_tim_bbox"]))
    key_to_ndet = dict(zip(df["stem"], df["n_det"]))

    def strat_class(key):
        n = key_to_ndet.get(key, 0)
        if n == 0:
            return 0  # hard negative
        return 2 if key_to_tim.get(key, False) else 1

    strat = [strat_class(key) for key in keys]

    hn_n = strat.count(0)
    nontim_n = strat.count(1)
    tim_n = strat.count(2)
    print(f"  Tim Hortons : {tim_n}  |  Non-Tim cups : {nontim_n}  |  Hard negatives : {hn_n}")

    # ---- 80/20 stratified split -----------------------------------------------
    tv_keys, test_keys, tv_strat, test_strat = train_test_split(
        keys, strat,
        test_size=args.test_size,
        random_state=seed,
        stratify=strat,
    )
    print(f"\n  Train+CV : {len(tv_keys)}  |  Test : {len(test_keys)}")

    # ---- clean previous outputs -----------------------------------------------
    for split in ("train", "val"):
        for parent in ("images", "labels"):
            d = YOLO_DIR / parent / split
            if d.exists():
                shutil.rmtree(d, onexc=_rm_readonly)
    for subdir in ("test", "folds", "trainval"):
        d = YOLO_DIR / subdir
        if d.exists():
            shutil.rmtree(d, onexc=_rm_readonly)

    # ---- held-out test set ----------------------------------------------------
    print("\nPopulating test set...")
    missing = populate_split(
        test_keys, YOLO_DIR / "test" / "images", YOLO_DIR / "test" / "labels",
        images_dir=images_dir,
    )
    if missing:
        print(f"  WARNING: {len(missing)} test keys had no matching image")

    write_data_yaml(
        YOLO_DIR / "test" / "data.yaml",
        root=YOLO_DIR,
        train="trainval/images/train",
        val="test/images",
    )

    # ---- trainval (full 80%) for final retraining -----------------------------
    print("Populating trainval (full 80%)...")
    missing = populate_split(
        tv_keys,
        YOLO_DIR / "trainval" / "images" / "train",
        YOLO_DIR / "trainval" / "labels" / "train",
        images_dir=images_dir,
    )
    if missing:
        print(f"  WARNING: {len(missing)} trainval keys had no matching image")

    write_data_yaml(
        YOLO_DIR / "trainval" / "data.yaml",
        root=YOLO_DIR,
        train="trainval/images/train",
        val="test/images",
    )

    # ---- k-fold CV splits -----------------------------------------------------
    print(f"\nGenerating {k}-fold CV splits...")
    skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=seed)

    fold_record: dict[str, dict] = {}
    for fold_i, (train_idx, val_idx) in enumerate(skf.split(tv_keys, tv_strat)):
        ftrain = [tv_keys[i] for i in train_idx]
        fval = [tv_keys[i] for i in val_idx]

        fold_dir = YOLO_DIR / "folds" / f"fold_{fold_i}"
        populate_split(ftrain, fold_dir / "images" / "train", fold_dir / "labels" / "train",
                        images_dir=images_dir)
        populate_split(fval, fold_dir / "images" / "val", fold_dir / "labels" / "val",
                        images_dir=images_dir)
        write_data_yaml(
            fold_dir / "data.yaml", root=fold_dir, train="images/train", val="images/val"
        )

        fold_record[f"fold_{fold_i}"] = {"train": ftrain, "val": fval}
        print(f"  Fold {fold_i}: train={len(ftrain)}, val={len(fval)}")

    # ---- persist fold indices for reproducibility -----------------------------
    meta = {
        "seed": seed,
        "k_folds": k,
        "test_size": args.test_size,
        "n_total": len(keys),
        "n_trainval": len(tv_keys),
        "n_test": len(test_keys),
        "test_keys": test_keys,
        "trainval_keys": tv_keys,
        "folds": fold_record,
    }
    indices_path = YOLO_DIR / "fold_indices.json"
    indices_path.write_text(json.dumps(meta, indent=2))
    print(f"\nSaved fold indices -> {indices_path}")

    # ---- legacy data.yaml (backward compat) -----------------------------------
    write_data_yaml(
        YOLO_DIR / "data.yaml",
        root=YOLO_DIR,
        train="trainval/images/train",
        val="test/images",
    )
    print(f"Wrote {YOLO_DIR / 'data.yaml'}")

    # ---- sanity check ---------------------------------------------------------
    test_hn = sum(1 for s in test_strat if s == 0)
    test_nontim = sum(1 for s in test_strat if s == 1)
    test_tim = sum(1 for s in test_strat if s == 2)
    tv_hn = sum(1 for s in tv_strat if s == 0)
    tv_nontim = sum(1 for s in tv_strat if s == 1)
    tv_tim = sum(1 for s in tv_strat if s == 2)
    print("\n-- Sanity Check ---")
    print(f"  Test      : {len(test_keys)} images  "
          f"(Tim={test_tim}, NonTim={test_nontim}, HardNeg={test_hn})")
    print(f"  Train+CV  : {len(tv_keys)} images  "
          f"(Tim={tv_tim}, NonTim={tv_nontim}, HardNeg={tv_hn})")
    for fold_i in range(k):
        fd = YOLO_DIR / "folds" / f"fold_{fold_i}"
        nt = len(list((fd / "images" / "train").iterdir()))
        nv = len(list((fd / "images" / "val").iterdir()))
        print(f"  Fold {fold_i}    : train={nt}, val={nv}")
    print("-------------------\n")
    print(f"Done! {k}-fold CV directories ready.")
    print(f"Next: python optuna_search.py --n-trials 50 --epochs-per-trial 20 --k-folds {k}")


if __name__ == "__main__":
    main()
