"""
prepare_yolo_split.py

Organises the flat YOLO labels into a stratified 80/20 train/val split and
creates a data.yaml that Ultralytics YOLOv8 can consume directly.

Layout produced:
  data/derived/yolo/
    images/
      train/   <- symlinks to data/images/<key>.jpg  (no data duplication)
      val/
    labels/
      train/   <- .txt files moved from the flat labels/ directory
      val/
    data.yaml  <- rewritten with absolute paths
"""

import shutil
import pathlib
import pandas as pd
from sklearn.model_selection import train_test_split

# ── paths ────────────────────────────────────────────────────────────────────
REPO_ROOT   = pathlib.Path(__file__).parent.resolve()
IMAGES_DIR  = REPO_ROOT / "data" / "images"
LABELS_FLAT = REPO_ROOT / "data" / "derived" / "yolo" / "labels"
YOLO_DIR    = REPO_ROOT / "data" / "derived" / "yolo"
SAMPLES_PQ  = REPO_ROOT / "data" / "index" / "samples.parquet"
DATA_YAML   = YOLO_DIR / "data.yaml"

SPLITS = ("train", "val")

# ── helpers ──────────────────────────────────────────────────────────────────

def clean_split_dirs():
    """Remove any previous train/val directories so we start fresh."""
    for split in SPLITS:
        img_dir = YOLO_DIR / "images" / split
        lbl_dir = YOLO_DIR / "labels" / split
        for d in (img_dir, lbl_dir):
            if d.exists():
                shutil.rmtree(d)
            d.mkdir(parents=True, exist_ok=True)

# ── main ─────────────────────────────────────────────────────────────────────

def main():
    # 1. collect all labelled image keys
    label_files = sorted(LABELS_FLAT.glob("*.txt"))
    if not label_files:
        raise FileNotFoundError(f"No .txt files found in {LABELS_FLAT}")

    keys = [f.stem for f in label_files]           # e.g. "-1P1ZHLBxgE_6d945ccd7e68bb31"
    print(f"Found {len(keys)} labelled images.")

    # 2. load samples.parquet to get stratification column
    # NOTE: use has_tim_bbox (no nulls, 543 True) — not is_tim_hortons_bbox which has 420 nulls
    df = pd.read_parquet(SAMPLES_PQ, columns=["image_key", "has_tim_bbox"])
    # image_key in parquet looks like "images/<stem>.jpg" — strip both parts
    df["image_key_stem"] = (
        df["image_key"]
        .str.replace(r"^images/", "", regex=True)
        .str.replace(r"\.(jpg|jpeg|png|webp)$", "", regex=True)
    )

    key_to_tim = dict(zip(df["image_key_stem"], df["has_tim_bbox"]))

    # map each key → Tim Hortons flag (default False if not found)
    strat_labels = [int(bool(key_to_tim.get(k, False))) for k in keys]

    tim_count     = sum(strat_labels)
    non_tim_count = len(strat_labels) - tim_count
    print(f"  Tim Hortons images : {tim_count}  (using has_tim_bbox)")
    print(f"  Non-Tim Hortons    : {non_tim_count}")

    # 3. stratified 80 / 20 split
    train_keys, val_keys, train_labels, val_labels = train_test_split(
        keys,
        strat_labels,
        test_size=0.20,
        random_state=42,
        stratify=strat_labels,
    )

    # 4. prepare output directories
    clean_split_dirs()

    # 5. create symlinks for images + copy label files
    missing_images = []

    for split, split_keys in (("train", train_keys), ("val", val_keys)):
        img_out = YOLO_DIR / "images" / split
        lbl_out = YOLO_DIR / "labels" / split

        for key in split_keys:
            # -- image symlink --
            # try common extensions
            img_src = None
            for ext in (".jpg", ".jpeg", ".png", ".webp"):
                candidate = IMAGES_DIR / (key + ext)
                if candidate.exists():
                    img_src = candidate
                    break

            if img_src is None:
                missing_images.append(key)
            else:
                link = img_out / img_src.name
                if not link.exists():
                    link.symlink_to(img_src.resolve())

            # -- label file copy --
            lbl_src = LABELS_FLAT / (key + ".txt")
            lbl_dst = lbl_out / (key + ".txt")
            if lbl_src.exists() and not lbl_dst.exists():
                shutil.copy2(lbl_src, lbl_dst)

    if missing_images:
        print(f"\nWARNING: {len(missing_images)} label keys had no matching image file.")
        for k in missing_images[:10]:
            print(f"  {k}")

    # 6. rewrite data.yaml with absolute path
    yaml_content = f"""# Auto-generated by prepare_yolo_split.py
path: {YOLO_DIR}
train: images/train
val: images/val

nc: 2
names:
  0: NonTimHortonsCup
  1: TimHortonsCup
"""
    DATA_YAML.write_text(yaml_content)
    print(f"\nWrote {DATA_YAML}")

    # 7. sanity-check printout
    print("\n── Sanity Check ─────────────────────────────────────────────")
    for split, split_keys, split_strat in (
        ("train", train_keys, train_labels),
        ("val",   val_keys,   val_labels),
    ):
        img_dir = YOLO_DIR / "images" / split
        lbl_dir = YOLO_DIR / "labels" / split
        n_img = len(list(img_dir.iterdir()))
        n_lbl = len(list(lbl_dir.iterdir()))
        n_tim = sum(split_strat)
        n_non = len(split_strat) - n_tim
        print(f"  {split:5s}  images={n_img}  labels={n_lbl}  "
              f"Tim={n_tim} ({n_tim/len(split_strat)*100:.1f}%)  "
              f"NonTim={n_non} ({n_non/len(split_strat)*100:.1f}%)")
    print("─────────────────────────────────────────────────────────────\n")
    print("Done! You can now run: python train_yolov8_mlflow.py")


if __name__ == "__main__":
    main()

